---

- name: install requirements
  become: true
  become_user: root
  apt: name="{{ item }}" state='present' update_cache='yes' cache_valid_time='3600'
  with_items:
   - build-essential
   - unzip
   - python-pip
   - python-dev
   - git
  tags:
    - packages

- name: download packer
  get_url: url="{{packer_url}}" dest='/tmp/packer.zip'

- name: unarchive packer
  sudo: true
  unarchive: src='/tmp/packer.zip' dest="{{packer_install_dir}}" copy='no' creates="{{packer_install_dir}}/packer"

- name: create /var/log/packer.log
  copy:
    content: ''
    force: no
    dest: /var/log/packer.log
    owner: "{{deploy_user}}"
    group: "{{deploy_group}}"
  become: true
  become_user: root
